services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5500:5500
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Monta el archivo redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    